package com.example.health_assistant.features.journal.domain.usecase

import android.util.Log
import com.example.health_assistant.features.journal.domain.ActivityCard
import com.example.health_assistant.features.journal.domain.ActivityCardRepository
import java.time.LocalDate
import javax.inject.Inject

/**
 * Use case for generating daily activity cards with real health metrics
 * Handles the 3 essential metrics: steps, calories, heart points
 */
class GenerateActivityCardUseCase @Inject constructor(
    private val activityCardRepository: ActivityCardRepository
) {

    /**
     * Generate activity card for a specific date with the 3 essential metrics
     */
    suspend fun generateCardForDate(
        date: LocalDate,
        stepCount: Int = 0,
        caloriesBurned: Int = 0,
        heartPoints: Int = 0
    ): Result<ActivityCard> {
        return try {
            val existingCard = activityCardRepository.getActivityCardByDate(date)

            val cardToSave = if (existingCard != null) {
                // CRITICAL FIX: Preserve the original ID when updating an existing card.
                // This ensures Room's REPLACE strategy works correctly.
                existingCard.copy(
                    stepCount = stepCount,
                    caloriesBurned = caloriesBurned,
                    heartPoints = heartPoints
                )
            } else {
                // Create a new card. The ID will be 0 by default and auto-generated by Room.
                ActivityCard(
                    date = date,
                    stepCount = stepCount,
                    caloriesBurned = caloriesBurned,
                    heartPoints = heartPoints
                )
            }

            // Save the new or updated card. Room will either INSERT or REPLACE.
            val savedCardId = activityCardRepository.insertActivityCard(cardToSave)

            // If a new card was inserted, its ID might have been generated.
            // Return the card with the correct ID.
            val finalCard = if (existingCard == null) cardToSave.copy(id = savedCardId) else cardToSave

            Result.success(finalCard)
        } catch (e: Exception) {
            Log.e("GenerateActivityCardUseCase", "Error generating or updating card for date $date", e)
            Result.failure(e)
        }
    }
}